// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"
)

type Branch struct {
	ID          int32        `json:"id"`
	Name        string       `json:"name"`
	Location    string       `json:"location"`
	Openingtime time.Time    `json:"openingtime"`
	Closingtime time.Time    `json:"closingtime"`
	Createdat   sql.NullTime `json:"createdat"`
	Updatedat   sql.NullTime `json:"updatedat"`
}

type Rating struct {
	ID        int32          `json:"id"`
	Iduser    int32          `json:"iduser"`
	Idservice int32          `json:"idservice"`
	Rating    int32          `json:"rating"`
	Comment   sql.NullString `json:"comment"`
	Createdat sql.NullTime   `json:"createdat"`
	Updatedat sql.NullTime   `json:"updatedat"`
}

type Reservation struct {
	ID        int32        `json:"id"`
	Iduser    int32        `json:"iduser"`
	Idservice int32        `json:"idservice"`
	Createdat sql.NullTime `json:"createdat"`
	Updatedat sql.NullTime `json:"updatedat"`
}

type Service struct {
	ID        int32        `json:"id"`
	Idbranch  int32        `json:"idbranch"`
	Name      string       `json:"name"`
	Type      string       `json:"type"`
	Detail    string       `json:"detail"`
	Pricing   string       `json:"pricing"`
	Duration  int32        `json:"duration"`
	Createdat sql.NullTime `json:"createdat"`
	Updatedat sql.NullTime `json:"updatedat"`
}

type User struct {
	ID          int32        `json:"id"`
	Fullname    string       `json:"fullname"`
	Photo       string       `json:"photo"`
	Email       string       `json:"email"`
	Phonenumber string       `json:"phonenumber"`
	Password    string       `json:"password"`
	Role        string       `json:"role"`
	Createdat   sql.NullTime `json:"createdat"`
	Updatedat   sql.NullTime `json:"updatedat"`
}
