// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBranches(ctx context.Context, id int32) error
	DeleteServices(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	GetBranch(ctx context.Context, id int32) (Branch, error)
	GetBranches(ctx context.Context) ([]Branch, error)
	GetRatings(ctx context.Context, idservice int32) ([]GetRatingsRow, error)
	GetService(ctx context.Context, id int32) (Service, error)
	GetServices(ctx context.Context) ([]Service, error)
	GetServicesByBranch(ctx context.Context, type_ string) ([]Service, error)
	GetUser(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	InsertBranch(ctx context.Context, arg InsertBranchParams) (Branch, error)
	InsertRating(ctx context.Context, arg InsertRatingParams) (Rating, error)
	InsertReservation(ctx context.Context, arg InsertReservationParams) (Reservation, error)
	InsertServices(ctx context.Context, arg InsertServicesParams) (Service, error)
	SelectReservation(ctx context.Context, iduser int32) ([]SelectReservationRow, error)
	UpdateBranches(ctx context.Context, arg UpdateBranchesParams) error
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdatePositionAndUsername(ctx context.Context, arg UpdatePositionAndUsernameParams) error
	UpdateServices(ctx context.Context, arg UpdateServicesParams) error
}

var _ Querier = (*Queries)(nil)
