// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	CreateProduk(ctx context.Context, arg CreateProdukParams) (Produk, error)
	DeleteProduk(ctx context.Context, idProduk int32) error
	GetAllProduk(ctx context.Context) ([]Produk, error)
	GetProduk(ctx context.Context, idProduk int32) (GetProdukRow, error)
	UpdateProduk(ctx context.Context, arg UpdateProdukParams) error
}

var _ Querier = (*Queries)(nil)
